// =============================================================================
// Music-generation prompt engine — style-agnostic, no synthesis.
// =============================================================================
// We do not produce audio locally. This turns a video's declarative `audio`
// brief (in VideoDef) + its real frame timings into a tool-agnostic music-
// generation PROMPT plus an ALIGNMENT PLAN, to feed a 3rd-party AI generator
// (ElevenLabs, DaVinci, Suno, Udio…). The returned track is then aligned so its
// drop lands on the cut's `drop` frame.
//
// Pure + dependency-free (no React, no Remotion, no fs) so it runs anywhere: a
// CLI, a test, or the studio. Given the same VideoDef it always emits the same
// prompt.

import type { AudioBeat, AudioBrief, VideoDef } from "./types";

const ROLE_TEXT: Record<AudioBeat["role"], string> = {
  intro: "sparse and tense — almost no drums; leave space, anticipatory",
  build: "energy climbing — kick/hats in, stabs, momentum",
  riser: "pull the drums back, then a rising riser (sweep + rising pitch + snare roll) into the drop",
  drop: "THE DROP — everything hits: full drums, the hook at its highest/brightest, the single most euphoric moment",
  sustain: "hold the energy — hook continues, driving",
  outro: "resolve and END ON ONE DECISIVE HIT (no fade-out)",
};

const fmtTime = (s: number): string => `${s.toFixed(2)}s`;

/** A beat with its resolved start/end time and duration share of the cut. */
type Section = {
  beat: AudioBeat;
  start: number;
  end: number;
  pct: number; // share of total duration, 0..100
};

/** Resolve a video's audio beats into timed sections (seconds + % of cut). */
export function sections(video: VideoDef): Section[] {
  const fps = video.fps ?? 30;
  const total = video.durationInFrames / fps;
  const beats = [...(video.audio?.beats ?? [])].sort((a, b) => a.frame - b.frame);
  return beats.map((beat, i) => {
    const start = beat.frame / fps;
    const end = i + 1 < beats.length ? beats[i + 1].frame / fps : total;
    return { beat, start, end, pct: ((end - start) / total) * 100 };
  });
}

/** The one drop beat (the payoff), or null if the brief declares none. */
export function dropSection(video: VideoDef): Section | null {
  return sections(video).find((s) => s.beat.role === "drop") ?? null;
}

/**
 * Build the full music-generation prompt + alignment plan for a video, as a
 * markdown string ready to write to the product's audio/PROMPT.md.
 * Throws if the video has no audio brief (nothing to score).
 */
export function buildPrompt(video: VideoDef): string {
  const brief = video.audio;
  if (!brief) {
    throw new Error(`Video "${video.id}" has no audio brief; nothing to generate.`);
  }
  const fps = video.fps ?? 30;
  const total = video.durationInFrames / fps;
  const secs = sections(video);
  const drop = dropSection(video);
  const tail = 3; // seconds of tail we ask the generator to overshoot by

  const cutTable = secs
    .map((s) => {
      const label = s.beat.label ?? s.beat.role;
      const range = `${fmtTime(s.start)}–${fmtTime(s.end)}`;
      return `| ${range} | ${label} | **${s.beat.role}** — ${ROLE_TEXT[s.beat.role]} |`;
    })
    .join("\n");

  const structure = secs
    .map((s) => {
      const a = Math.round((s.start / total) * 100);
      const b = Math.round((s.end / total) * 100);
      return `> - **${a}–${b}% — ${cap(s.beat.role)}:** ${ROLE_TEXT[s.beat.role]}.`;
    })
    .join("\n");

  const stinger = brief.stingerFrame != null ? brief.stingerFrame / fps : null;

  const alignment = [
    drop && `- \`drop_at\` = **${fmtTime(drop.start)}** (frame ${drop.beat.frame}) — the track's drop/biggest-energy moment must land here.`,
    (() => {
      const r = secs.find((s) => s.beat.role === "riser");
      return r && `- \`riser_from\` = **${fmtTime(r.start)}** (frame ${r.beat.frame}) — the track's riser/tension should begin here.`;
    })(),
    (() => {
      const o = secs.find((s) => s.beat.role === "outro");
      return o && `- \`outro_at\` = **${fmtTime(o.start)}** (frame ${o.beat.frame}) — resolve into the outro here.`;
    })(),
    stinger != null && `- \`stinger_at\` = **${fmtTime(stinger)}** (frame ${brief.stingerFrame}) — the closing decisive hit lands here.`,
    `- \`total\` = **${fmtTime(total)}** cut; aligned stem should run **~${fmtTime(total + 0.5)}** (cover + tail), never end early.`,
  ]
    .filter(Boolean)
    .join("\n");

  return `# Music-generation prompt — ${video.id}

> GENERATED by the shared prompt engine (\`engine/audio-prompt.ts\`) from this
> video's declarative \`audio\` brief + its real frame timings. Do not hand-edit;
> change the brief in the product's video and re-run \`npm run audio:prompt ${video.id}\`.

Video is **locked** (${video.durationInFrames}f / ${fmtTime(total)} @ ${fps}fps). Generate the
music with a 3rd-party AI tool (ElevenLabs / DaVinci / Suno / Udio), then align it
onto the cut per the ALIGNMENT PLAN below.

The cut we're scoring:

| Time | Beat | Music role |
|------|------|-----------|
${cutTable}

---

## THE PROMPT (tool-agnostic)

**Style (one line):**
> ${brief.style}

**Instrumentation:**
> ${brief.instrumentation}

**Tempo & key:**
> ${brief.tempoKey}

**Structure (scale these proportions to a ~${Math.ceil(total + tail)}s render):**
${structure}

**The hook:**
> ${brief.hook}

**Dynamics:**
> Wide dynamic range. The intro must be genuinely quiet and sparse so the drop
> lands with maximum contrast. Leave headroom — do NOT master to a brickwall.

**Negative prompt (exclude):**
> ${brief.exclude ?? "No vocals, no lyrics. No lo-fi. No fade-out ending (end on a hit). No genre drift mid-track."}

**Generation params:**
> Instrumental. Target length **≥ ${Math.ceil(total + tail)}s** (cut is ${fmtTime(total)} + tail).
> If the tool supports section tags, tag the sections above. Generate a few
> variations; pick the one whose drop is most euphoric and whose intro is most sparse.

---

## ALIGNMENT PLAN

Target timestamps in OUR cut (seconds):

${alignment}

**Alignment** is done by \`make_audio.py --align <track>\` (per product): it finds the
returned track's drop, time-shifts it onto \`drop_at\` (never pitch-shifts), and
pads/trims to cover the full cut. Then mux + verify the sound-designer's numeric
gates (drop within ~0.1s of \`drop_at\`, LRA ≥ 5 LU, True Peak ≤ −1.5 dBTP).
${brief.sfxNotes ? `\n**SFX stay synthesized** (not generated): ${brief.sfxNotes}` : ""}
`;
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
