"""Audio pipeline for the World Cup 2026 HYPE cut.

Music is GENERATED by a third-party AI tool (Suno/Udio/ElevenLabs) from
`audio/PROMPT.md`, NOT synthesized here — synthesis hit its ceiling. This script
does the two code-owned ends around that:

  SFX  (synthesized, in score.py):
      python make_audio.py WorldCup2026Hype --out out/audio
    writes <out>/<VideoId>-sfx.wav.

  MUSIC (align a generated track onto the locked cut):
      python make_audio.py WorldCup2026Hype --align path/to/generated.wav --out out/audio
    finds the track's drop, shifts it onto the cut's payoff frame, pads/trims to
    cover the full cut, and writes <out>/<VideoId>-music.wav.

Run both, then mux per CLAUDE.md. The old fully-synthesized `compose_music` in
score.py is superseded for delivery (scratch reference only).
"""

from __future__ import annotations

import argparse
import os

import numpy as np
import wave

from score import compose_sfx, load_audio, align_to_drop

SR = 48000


# =============================================================================
# Per-video config
# =============================================================================
# cuts / payoff_at / stinger are the film's actual frame constants (from the
# SCENES table in videos/hype.tsx, frames / 30). SFX land ON these, not near.
# drop_at is where a generated track's drop must be aligned to (the "ONE TROPHY"
# hero, frame 588). See audio/PROMPT.md for the full alignment plan.
VIDEOS: dict[str, dict] = {
    "WorldCup2026Hype": {
        "duration": 30.0,  # timeline is 900f / 30.00s
        "cuts": [0.0, 3.6, 7.2, 11.0, 15.0, 19.6, 24.0, 27.6],
        "payoff_at": 19.6,   # THE DROP — align the generated track's drop here
        "drop_at": 19.6,
        "stinger_at": 28.47,
        "riser_from": 15.0,
        "riser_to": 19.6,
    },
}


def write_wav(path: str, data: np.ndarray) -> None:
    """Write a float array (-1..1) as a 16-bit stereo WAV file."""
    if data.ndim == 1:
        data = np.stack([data, data])
    pcm = (np.clip(data, -1, 1) * 32767).astype(np.int16)
    inter = np.empty(pcm.shape[1] * 2, dtype=np.int16)
    inter[0::2] = pcm[0]
    inter[1::2] = pcm[1]
    with wave.open(path, "w") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(inter.tobytes())


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("video", choices=sorted(VIDEOS), help="composition id")
    ap.add_argument("--out", default="out/audio", help="output directory for the WAV files")
    ap.add_argument(
        "--align",
        metavar="TRACK",
        help="path to a generated music track (wav/mp3) to align onto the cut; "
        "if omitted, only SFX is written",
    )
    args = ap.parse_args()

    cfg = VIDEOS[args.video]
    os.makedirs(args.out, exist_ok=True)

    # SFX — always synthesized here.
    sfx_path = os.path.join(args.out, f"{args.video}-sfx.wav")
    write_wav(sfx_path, compose_sfx(cfg))
    print(f"wrote {sfx_path}")

    # MUSIC — align a generated track if one was supplied.
    if args.align:
        raw, in_sr = load_audio(args.align)
        aligned, offset, drop_found = align_to_drop(
            raw, in_sr, drop_at=cfg["drop_at"], total=cfg["duration"] + 0.5, out_sr=SR
        )
        music_path = os.path.join(args.out, f"{args.video}-music.wav")
        write_wav(music_path, aligned)
        print(
            f"wrote {music_path} — track drop @ {drop_found:.2f}s aligned to "
            f"{cfg['drop_at']:.2f}s (shift {offset:+.2f}s)"
        )
    else:
        print("no --align track given; music stem not written "
              "(generate one from audio/PROMPT.md, then re-run with --align)")


if __name__ == "__main__":
    main()
