"""Audio DSP for the World Cup 2026 HYPE cut.

Delivery entry points, taking the per-video cfg dict from make_audio.py:
  compose_sfx(cfg)                       -> stereo float SFX (-1..1)
  load_audio(path)                       -> (stereo float, sr) for a generated track
  align_to_drop(sig, sr, drop_at, total) -> (aligned stereo, offset, drop_found)

MUSIC is generated by a third-party AI tool from audio/PROMPT.md (synthesis hit
its ceiling); this module only ALIGNS that track onto the locked cut and
synthesizes the SFX (struck impacts on each cut, a chevron whoosh, a gold-logo
stinger).

`compose_music` below is the OLD fully-synthesized bed — SUPERSEDED for delivery,
kept only as a scratch reference. Do not ship it. See craft/sound-design.md.
"""

from __future__ import annotations

import subprocess

import numpy as np

SR = 48000


# ---------------------------------------------------------------------------
# generated-track ingest + alignment (the new music path)
# ---------------------------------------------------------------------------
def load_audio(path: str, sr: int = SR) -> tuple[np.ndarray, int]:
    """Decode any audio file to stereo float32 (-1..1) at `sr` via ffmpeg.

    Returns (stereo array shape (2, n), sr). Uses ffmpeg so it reads wav/mp3/
    m4a/flac — whatever the generator hands back.
    """
    cmd = [
        "ffmpeg", "-v", "error", "-i", path,
        "-f", "f32le", "-acodec", "pcm_f32le", "-ac", "2", "-ar", str(sr), "-",
    ]
    raw = subprocess.run(cmd, capture_output=True, check=True).stdout
    data = np.frombuffer(raw, dtype=np.float32)
    stereo = data.reshape(-1, 2).T.copy()  # (2, n)
    return stereo, sr


def _find_drop(sig: np.ndarray, sr: int) -> float:
    """Locate the track's drop: the largest sustained jump in short-term energy.

    Computes RMS over 0.25s windows, then finds where a 1s trailing average steps
    up the most (the intro→drop transition). Returns the time in seconds.
    """
    mono = sig.mean(axis=0)
    win = int(0.25 * sr)
    if win < 1 or len(mono) < win * 4:
        return 0.0
    n_win = len(mono) // win
    rms = np.sqrt(np.mean(mono[: n_win * win].reshape(n_win, win) ** 2, axis=1) + 1e-12)
    # smooth over ~1s (4 windows) each side, look for the biggest upward step
    k = 4
    if n_win < 2 * k + 1:
        return float(np.argmax(rms) * win / sr)
    # trailing/leading k-window means; edges are one-sided so we zero them below.
    def _mean(a: np.ndarray) -> float:
        return float(a.mean()) if a.size else 0.0

    before = np.array([_mean(rms[max(0, i - k):i]) for i in range(n_win)])
    after = np.array([_mean(rms[i:i + k]) for i in range(n_win)])
    step = after - before
    # ignore the very start/end where windows are one-sided
    step[:k] = 0
    step[-k:] = 0
    return float(np.argmax(step) * win / sr)


def align_to_drop(
    sig: np.ndarray, sr: int, drop_at: float, total: float, out_sr: int = SR
) -> tuple[np.ndarray, float, float]:
    """Shift a generated track so its drop lands on `drop_at`, cover `total`s.

    Time-nudge only (never pitch-shift): trim the head if the track's drop is
    later than drop_at, pad the head with silence if earlier. Then pad/trim the
    tail so the stem runs exactly `total` seconds (never ends early).

    Returns (aligned stereo (2, total*out_sr), applied_offset_seconds, drop_found).
    """
    drop_found = _find_drop(sig, sr)
    offset = drop_at - drop_found  # +ve => pad head (drop too early); -ve => trim head
    n_total = int(total * out_sr)
    out = np.zeros((2, n_total), dtype=np.float32)

    shift = int(offset * out_sr)
    if shift >= 0:
        # pad head: place the track starting at `shift`
        end = min(n_total, shift + sig.shape[1])
        out[:, shift:end] = sig[:, : end - shift]
    else:
        # trim head: drop the first -shift samples
        src = sig[:, -shift:]
        end = min(n_total, src.shape[1])
        out[:, :end] = src[:, :end]
    return out, offset, drop_found


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _t(dur: float) -> np.ndarray:
    return np.linspace(0, dur, int(dur * SR), endpoint=False)


def _env(n: int, attack: float, release: float, sustain_end: float | None = None) -> np.ndarray:
    """Simple AR/ASR envelope over n samples; times in seconds."""
    e = np.ones(n)
    a = int(attack * SR)
    r = int(release * SR)
    if a > 0:
        e[:a] = np.linspace(0, 1, a)
    if r > 0:
        e[-r:] = np.linspace(1, 0, r)
    return e


def _place(buf: np.ndarray, sig: np.ndarray, at: float) -> None:
    """Add mono sig into mono buf starting at time `at` (clipped to buf length)."""
    start = int(at * SR)
    end = min(start + len(sig), len(buf))
    if start >= len(buf) or end <= start:
        return
    buf[start:end] += sig[: end - start]


def _soft(x: np.ndarray) -> np.ndarray:
    """Soft saturation — glue + a touch of warmth without hard clipping."""
    return np.tanh(x * 1.3) / np.tanh(1.3)


def _stereo(mid: np.ndarray, spread: np.ndarray | None = None) -> np.ndarray:
    if spread is None:
        return np.stack([mid, mid])
    return np.stack([mid + spread, mid - spread])


# ---------------------------------------------------------------------------
# musical material
# ---------------------------------------------------------------------------
# A minor tonic that lifts to its relative-major-ish brighter voicing at the
# payoff. Frequencies (Hz) — root A, with the stack a min triad, lifting up.
A1, A2, C3, E3, A3 = 55.0, 110.0, 130.81, 164.81, 220.0
# Lifted voicing at the turn: C major-ish brightness over the same low root.
C4, E4, G4 = 261.63, 329.63, 392.0


def _saw(freq: float, t: np.ndarray, n_partials: int = 12) -> np.ndarray:
    """Band-limited-ish saw via summed harmonics — richer than a sine for brass."""
    out = np.zeros_like(t)
    for k in range(1, n_partials + 1):
        out += np.sin(2 * np.pi * freq * k * t) / k
    return out / np.max(np.abs(out) + 1e-9)


# ---------------------------------------------------------------------------
# drum bus — the single biggest step from "bed" to "track"
# ---------------------------------------------------------------------------
def _kick(vel: float = 1.0) -> np.ndarray:
    """Punchy sine kick: fast pitch drop + click transient."""
    kt = _t(0.20)
    pitch = 150 * np.exp(-kt * 42) + 48          # snappier drop, tighter low end
    body = np.sin(2 * np.pi * np.cumsum(pitch) / SR) * np.exp(-kt * 8)
    click = (np.random.rand(len(kt)) * 2 - 1) * np.exp(-kt * 140) * 0.35
    return (body + click) * vel


def _snare(vel: float = 1.0) -> np.ndarray:
    """Clap/snare: noise burst + a little tonal body, on 2 & 4."""
    st = _t(0.22)
    noise = (np.random.rand(len(st)) * 2 - 1)
    # two quick echoes = a clap smear, not a single hit
    clap = np.zeros_like(st)
    for d in (0.0, 0.008, 0.016):
        e = np.exp(-(st - d).clip(0) * 55)
        clap += noise * e
    tone = (np.sin(2 * np.pi * 190 * st) + np.sin(2 * np.pi * 330 * st)) * np.exp(-st * 30)
    return (clap * 0.5 + tone * 0.4) * vel


def _hat(vel: float = 1.0, open_: bool = False) -> np.ndarray:
    """Closed/open hat: filtered noise, short."""
    ht = _t(0.09 if open_ else 0.035)
    noise = (np.random.rand(len(ht)) * 2 - 1)
    # crude highpass: subtract a smoothed version
    sm = np.convolve(noise, np.ones(8) / 8, mode="same")
    hp = noise - sm
    return hp * np.exp(-ht * (18 if open_ else 55)) * vel


def _sidechain(n: int, kick_times: list[float], depth: float = 0.75) -> np.ndarray:
    """Pumping gain curve that ducks on each kick and recovers — the 'produced' breath.

    Returns a (n,) gain array in [1-depth, 1]. Each kick drops the gain to
    (1-depth) instantly, then it eases back to 1 over ~one 8th note.
    """
    g = np.ones(n)
    recover = 60.0 / 128.0 / 2.0  # eighth note at 128bpm
    rn = int(recover * SR)
    shape = 1.0 - depth * (1.0 - (np.linspace(0, 1, rn) ** 0.6))  # fast down, eased up
    for at in kick_times:
        s = int(at * SR)
        if s >= n:
            break
        e = min(s + rn, n)
        # take the min so overlapping recoveries don't brighten a following duck
        g[s:e] = np.minimum(g[s:e], shape[: e - s])
    return g


BPM = 128.0
BEAT = 60.0 / BPM  # 0.46875s

# The hook: a short, syllabic motif over the A-minor tonic that repeats so the
# ear catches it (an anthem shout, not a pad). Scale degrees as Hz, one bar.
#   A  -  C  -  E  -  D  (call), answered higher at the turn.
HOOK = [220.0, 261.63, 329.63, 293.66]      # A4 C5 E5 D5 — the phrase
HOOK_HI = [329.63, 392.0, 523.25, 440.0]    # E5 G5 C6 A5 — lifted answer at drop


def _beatgrid(dur: float) -> np.ndarray:
    """All downbeat times up to dur."""
    return np.arange(0, dur, BEAT)


# ===========================================================================
# SUPERSEDED — the old fully-synthesized music bed. Music is now GENERATED
# (audio/PROMPT.md) and aligned via align_to_drop(). This is kept only as a
# scratch reference for the arrangement/cue frames; make_audio.py no longer
# calls it and it must NOT be shipped. See craft/sound-design.md (synthesis
# ceiling) and this product's NOTES.md.
# ===========================================================================
def compose_music(cfg: dict) -> np.ndarray:  # noqa: C901  (reference only)
    dur = cfg["duration"] + 0.5  # tail so it never ends early
    payoff = cfg["payoff_at"]
    n = int(dur * SR)
    mid = np.zeros(n)

    # -- arrangement sections (intensity envelope drives every layer) ----------
    # intro (cold open, sparse) -> build -> DROP at payoff (full) -> outro tail.
    build_in = cfg["cuts"][1]                 # drums enter here
    drop = payoff                             # the hero landing = the drop
    intensity = np.interp(
        _t(dur),
        [0, build_in, cfg["riser_from"], drop - 0.05, drop, dur],
        [0.15, 0.55, 0.80, 0.35, 1.0, 0.85],  # dip just before the drop = air, then slam
    )

    # -- kick: four-on-the-floor from build_in; drops out for the hero's air ----
    kick_times = [at for at in _beatgrid(dur)
                  if build_in <= at and not (drop - 0.35 <= at < drop)]
    for at in kick_times:
        vel = 0.85 * np.interp(at, [0, build_in, drop, dur], [0.4, 0.9, 1.0, 0.9])
        _place(mid, _kick(vel), at)

    # -- snare/clap on beats 2 & 4 (backbeat), from the build ------------------
    for at in _beatgrid(dur):
        beat_idx = round(at / BEAT)
        if at >= build_in and beat_idx % 2 == 1 and at < drop - 0.35:
            _place(mid, _snare(0.55), at)

    # -- hats: straight 8ths in the build, doubling to 16ths into the drop -----
    hat_grid = np.arange(build_in, dur, BEAT / 2)  # 8ths
    for at in hat_grid:
        if drop - 2.0 <= at < drop:                # 16th roll into the drop
            for sub in (0.0, BEAT / 4):
                _place(mid, _hat(0.28, open_=False), at + sub)
        elif at < drop - 0.35 or at >= drop:
            openhat = round(at / (BEAT / 2)) % 4 == 3
            _place(mid, _hat(0.30, open_=openhat), at)

    # -- harmonic bed: minor stack, lifting to a brighter voicing at the drop --
    def stack(freqs, t0, t1, level):
        seg_t = _t(t1 - t0)
        e = _env(len(seg_t), attack=0.20, release=0.4)
        s = np.zeros_like(seg_t)
        for f in freqs:
            s += _saw(f, seg_t, n_partials=10)
        _place(mid, s / len(freqs) * e * level, t0)

    stack([A2, C3, E3, A3], build_in, drop, 0.26)      # minor, before the turn
    stack([A2, C4, E4, G4], drop, dur, 0.40)           # brighter lift, held

    # -- deep sub root under everything, following the intensity ---------------
    tt = _t(dur)
    sub = np.sin(2 * np.pi * A1 * tt) + 0.5 * np.sin(2 * np.pi * A2 * tt)
    mid += 0.45 * sub * intensity

    # -- THE HOOK: the repeating lead motif, one note per beat, from the build --
    #    Detuned twin saws (a supersaw shout), answered higher at the drop.
    def play_hook(notes, t0, t1, level):
        i = 0
        at = t0
        while at < t1:
            f = notes[i % len(notes)]
            nt = _t(BEAT * 0.9)
            lead = (_saw(f, nt, 8) + _saw(f * 1.006, nt, 8)) * 0.5  # detune shimmer
            e = _env(len(nt), attack=0.01, release=0.12)
            _place(mid, lead * e * level, at)
            at += BEAT
            i += 1

    play_hook(HOOK, build_in, drop - 0.35, 0.22)       # call, under the build
    play_hook(HOOK_HI, drop, dur, 0.30)                # lifted answer, over the drop

    # -- riser resolving INTO the drop ----------------------------------------
    r0, r1 = cfg["riser_from"], cfg["riser_to"]
    rt = _t(r1 - r0)
    ramp = (rt / (rt[-1] + 1e-9)) ** 1.6
    noise = np.cumsum(np.random.rand(len(rt)) * 2 - 1)
    noise = noise / (np.max(np.abs(noise)) + 1e-9)
    tone = np.sin(2 * np.pi * (220 + 600 * ramp) * rt)
    _place(mid, (0.5 * noise + 0.5 * tone) * ramp * 0.5, r0)

    # -- boom impact on the drop downbeat -------------------------------------
    bt = _t(1.2)
    boom = np.sin(2 * np.pi * (70 * np.exp(-bt * 3) + 40) * bt) * np.exp(-bt * 2.5)
    _place(mid, boom * 0.8, drop)

    # -- SIDECHAIN: duck the whole bed to the kick (the produced 'pump') -------
    #    Applied to the sustained material only — drums are already transient.
    #    We approximate by ducking the full mix, which reads as the classic pump.
    sc = _sidechain(n, kick_times, depth=0.45)
    mid = mid * sc

    # -- SECTION DYNAMICS: ride the whole mix by the arrangement intensity so the
    #    intro is genuinely sparse and the drop genuinely slams (real LRA, not a
    #    flat wall). Curve exaggerated so quiet is quiet.
    mid = mid * (0.28 + 0.72 * intensity)

    mid = _soft(mid)
    # gentle stereo width on the highs via a short haas-ish offset
    spread = np.zeros_like(mid)
    off = int(0.008 * SR)
    spread[off:] = mid[:-off] * 0.14
    out = _stereo(mid, spread)
    peak = np.max(np.abs(out)) + 1e-9
    # leave headroom: normalise to 0.7 (was 0.9) so the mux mix isn't hot
    return out / peak * 0.7


def compose_sfx(cfg: dict) -> np.ndarray:
    dur = cfg["duration"] + 0.5
    n = int(dur * SR)
    mid = np.zeros(n)

    # --- impact on every hard cut: struck, inharmonic, short ---
    for i, at in enumerate(cfg["cuts"]):
        it = _t(0.35)
        # metallic hit: a few inharmonic partials + noise transient
        partials = [180, 330, 505, 790]
        hit = np.zeros_like(it)
        for p in partials:
            hit += np.sin(2 * np.pi * p * it) * np.exp(-it * 14)
        transient = (np.random.rand(len(it)) * 2 - 1) * np.exp(-it * 90)
        sig = (hit / len(partials) + transient * 0.6) * 0.7
        # the cold-open cut is soft (nothing to hit yet); later cuts harder
        sig *= 0.4 if i == 0 else 1.0
        _place(mid, sig, at)

    # --- whoosh into the chevrons (~4.6s) — a filtered noise sweep ---
    wt = _t(0.5)
    env = np.exp(-((wt - 0.25) ** 2) / (2 * 0.09 ** 2))
    whoosh = (np.random.rand(len(wt)) * 2 - 1) * env
    # give it a downward "pass-by" motion via amplitude tilt
    whoosh *= np.linspace(0.4, 1.0, len(wt))
    _place(mid, whoosh * 0.5, 4.55)

    # --- the closing stinger on the gold 2026 logo: decisive, bright, ringing ---
    st = _t(1.6)
    # a struck bell-metal chord (A + E + A octave), inharmonic, long ring
    bell = (
        np.sin(2 * np.pi * 220 * st)
        + 0.7 * np.sin(2 * np.pi * 330 * st)
        + 0.5 * np.sin(2 * np.pi * 440 * st * 1.003)  # slight detune shimmer
        + 0.3 * np.sin(2 * np.pi * 660 * st)
    )
    bell *= np.exp(-st * 3.0)
    # a sub thump under it
    thump = np.sin(2 * np.pi * (60 * np.exp(-st * 4) + 40) * st) * np.exp(-st * 4)
    stinger = (bell * 0.25 + thump * 0.7)
    _place(mid, stinger, cfg["stinger_at"])

    mid = _soft(mid)
    out = _stereo(mid)
    peak = np.max(np.abs(out)) + 1e-9
    return out / peak * 0.95


if __name__ == "__main__":  # pragma: no cover
    # quick self-test
    cfg = {
        "duration": 30.0,
        "cuts": [0.0, 3.6, 7.2, 11.0, 15.0, 19.6, 24.0, 27.6],
        "payoff_at": 20.07,
        "stinger_at": 28.47,
        "riser_from": 15.0,
        "riser_to": 20.07,
    }
    m = compose_music(cfg)
    s = compose_sfx(cfg)
    print("music", m.shape, "sfx", s.shape)
